package com.college.studentmanagement.config;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.ApplicationRunner;
import org.springframework.boot.ApplicationArguments;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

import com.college.studentmanagement.dao.RoleDao;
import com.college.studentmanagement.entity.Role;

/**
 * The schema is generated by Hibernate (ddl-auto=update), which leaves the role table empty.
 * Without the role rows, registration stores users with a null role and login fails with a
 * NullPointerException. This runner guarantees the roles exist and repairs users saved without one.
 */
@Component
public class RoleDataInitializer implements ApplicationRunner {

	public static final String ROLE_STUDENT = "ROLE_STUDENT";
	public static final String ROLE_TEACHER = "ROLE_TEACHER";

	private static final Logger logger = LoggerFactory.getLogger(RoleDataInitializer.class);

	@Autowired
	private RoleDao roleDao;

	@Override
	@Transactional
	public void run(ApplicationArguments args) {
		Role studentRole = findOrCreateRole(ROLE_STUDENT);
		Role teacherRole = findOrCreateRole(ROLE_TEACHER);

		int repairedStudents = roleDao.assignRoleWhereMissing("Student", studentRole);
		int repairedTeachers = roleDao.assignRoleWhereMissing("Teacher", teacherRole);

		if (repairedStudents > 0 || repairedTeachers > 0) {
			logger.warn("Assigned a default role to {} student(s) and {} teacher(s) that had no role.",
					repairedStudents, repairedTeachers);
		}
	}

	private Role findOrCreateRole(String roleName) {
		Role role = roleDao.findRoleByName(roleName);
		if (role == null) {
			logger.info("Role {} is missing, creating it.", roleName);
			role = roleDao.save(new Role(roleName));
		}
		return role;
	}
}
